# Generated by Django 3.2.14 on 2022-07-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
